"""
Writes verified test functions into the target test file using libcst.
Preserves formatting, comments, and all existing code exactly.
Auto-restores if anything goes wrong.
"""
from __future__ import annotations
import shutil
import time
import json
import libcst as cst
from pathlib import Path
from quell.core.models import GeneratedTest, QuellConfig, AuditEntry, VerificationStatus


class TestWriter:
    """
    Injects a verified test function into a test file using libcst.

    Never uses string concatenation. Always uses CST transformation.
    Backs up before writing. Restores on failure.

    Usage:
        writer = TestWriter(config)
        success = writer.write(generated_test, audit_log)
    """

    def __init__(self, config: QuellConfig):
        self.config = config
        config.audit_log_path.parent.mkdir(parents=True, exist_ok=True)

    def write(self, test: GeneratedTest, mutant_id: str) -> bool:
        """
        Write a verified test to the test file.
        Returns True on success, False on failure.
        """
        test_file = test.test_file_path

        # Create file if it doesn't exist
        if not test_file.exists():
            test_file.parent.mkdir(parents=True, exist_ok=True)
            test_file.write_text("# Generated by Quell\nimport pytest\n\n", encoding="utf-8")

        # Backup
        backup = test_file.with_suffix(f".{int(time.time())}.bak")
        shutil.copy2(test_file, backup)

        try:
            existing_source = test_file.read_text(encoding="utf-8")
            new_source = self._inject_test(existing_source, test.test_code)

            # Validate the new source parses correctly
            cst.parse_module(new_source)

            test_file.write_text(new_source, encoding="utf-8")
            backup.unlink()

            self._append_audit(AuditEntry(
                mutant_id=mutant_id,
                action="test_written",
                file_path=test_file,
                test_function_name=test.test_function_name,
                verification_status=VerificationStatus.VERIFIED,
            ))
            return True

        except Exception:
            # Restore backup
            if backup.exists():
                shutil.copy2(backup, test_file)
                backup.unlink()

            self._append_audit(AuditEntry(
                mutant_id=mutant_id,
                action="write_failed",
                file_path=test_file,
                test_function_name=test.test_function_name,
            ))
            return False

    def _inject_test(self, existing_source: str, new_test_code: str) -> str:
        """
        Parse existing source as CST and append the new test function.
        Uses libcst to ensure formatting is preserved.
        """
        module = cst.parse_module(existing_source)
        new_test_module = cst.parse_module(new_test_code)

        new_statements = list(module.body) + list(new_test_module.body)
        new_module = module.with_changes(body=new_statements)
        return new_module.code

    def _append_audit(self, entry: AuditEntry) -> None:
        """Append an audit entry to the JSONL audit log."""
        with self.config.audit_log_path.open("a") as f:
            f.write(entry.model_dump_json() + "\n")
